# Generated by Django 5.1.2 on 2024-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_remove_teacher_email_remove_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
