# Generated by Django 5.1.2 on 2024-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='enrollment_number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
