# Generated by Django 5.1.2 on 2024-12-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='student_answers/'),
        ),
    ]
