# Generated by Django 5.1.2 on 2024-12-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_email_remove_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
